Use 1>&2 instead of >> /dev/stderr

diff --git a/run b/run
--- a/run
+++ b/run
@@ -17,7 +17,7 @@ do
     then
         NAMES+=( "$NAME" )
     else
-        echo "Could not find 'scripts/$NAME', using '$ARG'" >> /dev/stderr
+        echo "Could not find 'scripts/$NAME', using '$ARG'" 1>&2
         NAMES+=( "$ARG" )
     fi
 done
@@ -38,7 +38,7 @@ done
 
 if [[ "$#" -eq 0 ]]
 then
-    echo "No tests given, running all" >> /dev/stderr
+    echo "No tests given, running all" 1>&2
     run all
 else
     run "${RESULTS[@]}"
diff --git a/scripts/astplugin-test b/scripts/astplugin-test
--- a/scripts/astplugin-test
+++ b/scripts/astplugin-test
@@ -2,7 +2,7 @@
 set -e
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     exit 1
 }
 
diff --git a/scripts/cabal-test b/scripts/cabal-test
--- a/scripts/cabal-test
+++ b/scripts/cabal-test
@@ -47,14 +47,14 @@ then
         echo "Running hsConfig in $PWD"
         if ! hsConfig
         then
-            echo "hsConfig in '$DIR'" >> /dev/stderr
+            echo "hsConfig in '$DIR'" 1>&2
             ERR=1
         fi
 
         [[ "$ERR" -eq 0 ]] && while read -r TEST
         do
             cabal test "$TEST" || {
-                echo "Test suite '$TEST' in '$DIR' failed" >> /dev/stderr
+                echo "Test suite '$TEST' in '$DIR' failed" 1>&2
                 ERR=1
             }
         done < <(grep "test-suite" < "$FILE" | sed -e 's/^test-suite *\(.*\)$/\1/g')
diff --git a/scripts/git-local b/scripts/git-local
--- a/scripts/git-local
+++ b/scripts/git-local
@@ -31,7 +31,7 @@ do
     LOCAL="/home/chris/Programming/repos/$REPO"
     [[ -e "$LOCAL" ]] || {
         ERR=1
-        echo "Could not find '$LOCAL'" >> /dev/stderr
+        echo "Could not find '$LOCAL'" 1>&2
         continue
     }
 
@@ -40,7 +40,7 @@ do
     pushd "$LOCAL" > /dev/null
       grep "url = $REMOTE" < config > /dev/null || {
         ERR=1
-        echo "Repo '$LOCAL' doesn't have remote '$REMOTE'" >> /dev/stderr
+        echo "Repo '$LOCAL' doesn't have remote '$REMOTE'" 1>&2
       }
     popd > /dev/null
 done < <(cached)
diff --git a/scripts/mlspec-test b/scripts/mlspec-test
--- a/scripts/mlspec-test
+++ b/scripts/mlspec-test
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     exit 1
 }
 
diff --git a/scripts/nix-eval-installed-test b/scripts/nix-eval-installed-test
--- a/scripts/nix-eval-installed-test
+++ b/scripts/nix-eval-installed-test
@@ -4,7 +4,7 @@
 # directory
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     exit 1
 }
 
diff --git a/scripts/nix-eval-stdio b/scripts/nix-eval-stdio
--- a/scripts/nix-eval-stdio
+++ b/scripts/nix-eval-stdio
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 
 function fail {
-    echo -e "FAIL: $1" >> /dev/stderr
+    echo -e "FAIL: $1" 1>&2
     exit 1
 }
 
 function tryNixEval {
     CODE=$(codeNixEval)
-    echo -e "RUNNING:\n\n$CODE\n\n---\n" >> /dev/stderr
+    echo -e "RUNNING:\n\n$CODE\n\n---\n" 1>&2
     echo "$CODE" | nix-shell -p 'haskellPackages.ghcWithPackages (h: [ h.nix-eval ])' --run runhaskell
 }
 
@@ -25,12 +25,12 @@ function testNixEval {
 
     [[ "x$RESULT" = "xTrue" ]] || fail "Wrong value"
 
-    echo "testNixEval passed" >> /dev/stderr
+    echo "testNixEval passed" 1>&2
 }
 
 function tryMLSpec {
     CODE=$(codeMLSpec)
-    echo -e "RUNNING:\n\n$CODE\n\n---\n" >> /dev/stderr
+    echo -e "RUNNING:\n\n$CODE\n\n---\n" 1>&2
 
     echo "$CODE" | nix-shell -p 'haskellPackages.ghcWithPackages (h: [ h.mlspec h.nix-eval ])' --run runhaskell ||
         fail "Attempting to evaluate MLSpec-using code aborted"
@@ -62,7 +62,7 @@ function testMLSpec {
     [[ "$ALL_LINES" -eq "$JSON_LINES" ]] ||
         fail "Only $JSON_LINES/$ALL_LINES look like JSON:\n$RESULT"
 
-    echo "testMLSpec passed" >> /dev/stderr
+    echo "testMLSpec passed" 1>&2
 }
 
 echo "Running tests with debug"
diff --git a/scripts/nix-eval-test b/scripts/nix-eval-test
--- a/scripts/nix-eval-test
+++ b/scripts/nix-eval-test
@@ -5,7 +5,7 @@
 # from the source directory
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     exit 1
 }
 
@@ -26,7 +26,7 @@ popd > /dev/null
 DIR=$(mktemp -d -t 'nix-eval-test-XXXXX')
 pushd "$DIR" > /dev/null ||
     fail "Couldn't pushd temp dir '$DIR'"
-echo "Made temp directory '$DIR'" >> /dev/stderr
+echo "Made temp directory '$DIR'" 1>&2
 
 git clone http://chriswarbo.net/git/nix-eval.git nix-eval ||
     fail "Couldn't clone nix-eval"
diff --git a/scripts/panhandle b/scripts/panhandle
--- a/scripts/panhandle
+++ b/scripts/panhandle
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 echo "Checking for panhandle binary"
 nix-shell --show-trace -p panhandle -p which --run 'which panhandle' || {
-    echo "panhandle binary not installed" >> /dev/stderr
+    echo "panhandle binary not installed" 1>&2
     exit 1
 }
 
@@ -18,12 +18,12 @@ echo "Got unwrap '$UNWRAP'"
 
 HTML=$(echo "$UNWRAP" | nix-shell -p pandoc -p panhandle --run \
                             "pandoc --filter panhandle -f markdown -t html") || {
-    echo "Failed to check JSON" >> /dev/stderr
+    echo "Failed to check JSON" 1>&2
     exit 1
 }
 echo "Got HTML '$HTML'"
 
 echo "$HTML" | grep '<em>foo</em>' || {
-    echo "Didn't unwrap *foo* in '$HTML'" >> /dev/stderr
+    echo "Didn't unwrap *foo* in '$HTML'" 1>&2
     exit 1
 }
diff --git a/scripts/render b/scripts/render
--- a/scripts/render
+++ b/scripts/render
@@ -19,7 +19,7 @@ then
         pushd "$DIR"
         if ! ./render.sh
         then
-            echo "$SCRIPT failed" >> /dev/stderr
+            echo "$SCRIPT failed" 1>&2
             exit 1
         fi
     done < <(echo "$LINES")
diff --git a/scripts/test-scripts-included b/scripts/test-scripts-included
--- a/scripts/test-scripts-included
+++ b/scripts/test-scripts-included
@@ -40,7 +40,7 @@ cached > /dev/null
 echo "Cache filled"
 
 function fail {
-    echo "FAIL: $1" >> /dev/stderr
+    echo "FAIL: $1" 1>&2
     [[ "$FULL" -eq 1 ]] || exit 1
 }
 
