Clean up output

diff --git a/scripts/check-tex b/scripts/check-tex
--- a/scripts/check-tex
+++ b/scripts/check-tex
@@ -5,29 +5,31 @@ DIR="/home/chris/Documents/ArchivedPapers"
 function exists {
     if [[ -e "$1" ]]
     then
+        echo "Found '$1'"
         return
     fi
 
     if [[ -e "$DIR/$1" ]]
     then
+        echo "Found '$DIR/$1'"
         return
     fi
 
-    FILE=$(basename "$1")
+    B=$(basename "$1")
     for PREFIX in "/home/chris/Documents" "/home/chris/Documents/ArchivedPapers"
     do
-        if [[ -e "$PREFIX/$FILE" ]]
+        if [[ -e "$PREFIX/$B" ]]
         then
-            echo "No such file '$1', but did find '$PREFIX/$FILE'"
+            echo "No such file '$1', but did find '$PREFIX/$B'" 1>&2
             exit 1
         fi
     done
 
-    echo "Could not find $1" >> /dev/stderr
+    echo "Could not find $1" 1>&2
     exit 1
 }
 
-echo "Checking localfiles exist" >> /dev/stderr
+echo "Checking localfiles exist"
 
 BIB="/home/chris/Writing/Bibtex.bib"
 
@@ -35,7 +37,9 @@ exists "$BIB"
 
 while read -r FILE
 do
+    echo "Checking '$FILE'"
     exists "$FILE"
+
     NORM=$(basename "$FILE" | tr '[:upper:]' '[:lower:]')
     EXT=$(echo "$NORM" | rev | cut -d '.' -f 1   | rev)
     ALLOWED=0
@@ -43,19 +47,23 @@ do
     do
         [[ "x$EXT" = "x$OKEXT" ]] && ALLOWED=1
     done
-    [[ "$ALLOWED" -eq 1 ]] || {
-        echo "Filename '$FILE' indicates an invalid format" >> /dev/stderr
+    if [[ "$ALLOWED" -eq 1 ]]
+    then
+        echo "'$FILE' has acceptable filename"
+    else
+        echo "Filename '$FILE' indicates an invalid format" 1>&2
         exit 1
-    }
+    fi
 done < <(grep -o 'localfile[ \t]*=[ \t]*".*"' < "$BIB" |
          grep -o '".*"'                                |
          grep -o '[^"]*')
 
-echo "Trying bibclean" >> /dev/stderr
+echo "Trying bibclean"
 
 RAWBIB=$(nix-shell -p bibclean \
                    --run "bibclean -output-file /dev/null 2>&1 < $BIB") || {
-    echo "RAWBIB: $RAWBIB"
+    echo "bibclean exited with code '$?'" 1>&2
+    echo "RAWBIB: $RAWBIB" 1>&2
     exit 1
 }
 
@@ -68,25 +76,31 @@ KEEP=$(echo "$RAWBIB"                         |
       grep -v "Unexpected value in ..volume" |
       grep -v "Unexpected value in ..month")
 
-[[ -z "$KEEP" ]] || {
-    echo "Nonempty stderr: '$KEEP'"
+if [[ -z "$KEEP" ]]
+then
+    echo "No suspicious output from bibclean"
+else
+    echo "bibclean gave the following suspicious output:" 1>&2
+    echo "$KEEP" 1>&2
     exit 1
-}
-
-# Even though we haven't failed, we still show everything, for completeness
-echo "$RAWBIB"
+fi
 
 echo "Trying bibtool"
 
 RAWBIB=$(nix-shell -p bibtool --run "bibtool < $BIB 2>&1 1> /dev/null") || {
-    echo "RAWBIB: $RAWBIB"
+    echo "bibtool exited with code $?" 1>&2
+    echo "$RAWBIB" 1>&2
     exit 1
 }
 
-[[ -z "$RAWBIB" ]] || {
-    echo "Nonempty stderr: '$RAWBIB'"
+if [[ -z "$RAWBIB" ]]
+then
+    echo "No suspicious output from bibtool"
+else
+    echo "bibtool gave the following suspicious output" 1>&2
+    echo "$RAWBIB" 1>&2
     exit 1
-}
+fi
 
 echo "Trying bibtex"
 
@@ -105,22 +119,26 @@ cat << 'EOF' > "check-tex.tex"
 \end{document}
 EOF
 
-{ latex check-tex && bibtex check-tex; } || {
-    echo "Error running latex and/or bibtex"
+if { latex check-tex && bibtex check-tex; }
+then
+    echo "Ran latex and bibtex on '$BIB'"
+else
+    echo "Error running latex and/or bibtex" 1>&2
     exit 1
-}
+fi
 
 popd
 
 echo "Checking for dodgy keys"
 
-grep "^@misc{zzzzz" < "$BIB" && {
+if grep "^@misc{zzzzz" < "$BIB"
+then
     echo "Dodgy keys found; either look up a proper citation, or remove them"
-}
+fi
 
 exit 0
 
-# Tools to try:
+# Other tools to try:
 lacheck
 ChkTeX
 "http://www.ctan.org/tex-archive/support/check/"
