Disable flaky git commit checking

diff --git a/scripts/git-pushed b/scripts/git-pushed
--- a/scripts/git-pushed
+++ b/scripts/git-pushed
@@ -1,10 +1,46 @@
 #!/usr/bin/env bash
 
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
+
+function fail {
+    msg "FAIL: $1"
+    ERR=1
+    [[ "$FULL" -eq 1 ]] || exit 1
+}
+
 function repos {
     # Find git repos based on their .git directories
-    locate -e "/home/chris/*/.git" |
-    grep -v "/Backups/"            |
-    grep -v "/git-html"
+    locate -e "/home/chris/*/.git"
+}
+
+function msg {
+    echo -e "$1" >> /dev/stderr
+}
+
+function remotes {
+    # We should always be pushing to origin and github; we don't enforce
+    # anything else since they're case-by-case. For example, we might
+    # have a read-only "upstream" for fetching, with pushes going via
+    # pull requests from "github"
+    git remote | while read -r R
+    do
+        [[ "x$R" = "xorigin" ]] && echo "$R"
+        [[ "x$R" = "xgithub" ]] && echo "$R"
+    done
+}
+
+function branches {
+    git branch | cut -c 3- | grep -v '^('
+}
+
+function checkBranch {
+    git ls-remote "$1" 2> /dev/null | cut -f 2 |
+                                      grep -Fx "refs/heads/$2" > /dev/null || {
+        fail "'$REPO' branch '$BRANCH' not on remote '$1'"
+        return 1
+    }
 }
 
 function data {
@@ -17,49 +53,54 @@ function data {
     ls -d1 /home/chris/Programming/repos/*.git
 }
 
+function skip {
+    grep -v "opencl-horde" |
+    grep -v "/Backups/"    |
+    grep -v "/git-html"
+}
+
 function cached {
-    ./helpers/cache.sh "git-pushed" < <(data)
+    ./helpers/cache.sh "git-pushed" < <(data | skip) | skip
 }
 
 cached > /dev/null
 
 ERR=0
 
-while read -r REPO
-do
-    [[ -e "$REPO" ]] || { echo "Skipping non-existent '$REPO'"; continue; }
+function checkRepos {
+    while read -r REPO
+    do
+        [[ -e "$REPO" ]] || { echo "Skipping non-existent '$REPO'"; continue; }
 
-    # `git status` also lists unpushed commits but it doesn't work in bare repos
+        pushd "$REPO" > /dev/null
 
-    pushd "$REPO" > /dev/null
+        # Skip repos with no remote
+        [[ -z "$(git remote)" ]] && continue
 
-    # Skip repos with no remote
-    [[ -z "$(git remote)" ]] && continue
+        checkRemotes
 
-    # Lists unpushed commits and untracked branches
+        popd > /dev/null
+    done < <(cached)
+}
+
+function checkRemotes {
+    # Look for unpushed commits and missing branches. `git status` also lists
+    # unpushed commits but it doesn't work in bare repos
+    while read -r REMOTE
+    do
+        checkBranches "$REMOTE"
+    done < <(remotes)
+}
+
+function checkBranches {
+    MISSINGBRANCHES=0
     while read -r BRANCH
     do
-        while read -r REMOTE
-        do
-            # Always push to origin and github; anything else is case-by-case.
-            # For example, we might have a read-only "upstream" for fetching,
-            # with pushes going via pull requests from "github"
-            [[ "x$REMOTE" = "xorigin" ]] ||
-            [[ "x$REMOTE" = "xgithub" ]] ||
-            continue
+        checkBranch "$1" "$BRANCH" || MISSINGBRANCHES=1
+    done < <(branches)
+    return "$MISSINGBRANCHES"
+}
 
-            UNPUSHED=$(git cherry "$BRANCH" "$REMOTE/$BRANCH" 2>&1) || {
-                echo "Untracked branches in '$REPO' '$REMOTE/$BRANCH'" >> /dev/stderr
-                echo "$UNPUSHED"
-            }
-            echo "$UNPUSHED" | grep "^+" > /dev/null && {
-                ERR=1
-                echo "Unpushed commits in '$REPO' '$REMOTE/$BRANCH'" >> /dev/stderr
-            }
-        done < <(git remote)
-    done < <(git branch | cut -c 3-)
-
-    popd > /dev/null
-done < <(cached)
+checkRepos
 
 exit "$ERR"
