Get nix-eval-stdio to work

diff --git a/scripts/nix-eval-stdio b/scripts/nix-eval-stdio
--- a/scripts/nix-eval-stdio
+++ b/scripts/nix-eval-stdio
@@ -5,15 +5,64 @@ function fail {
     exit 1
 }
 
-function mkTrue {
-  cat <<'EOF' | nix-shell -p 'haskellPackages.ghcWithPackages (h: [ h.nix-eval ])' --run runhaskell
+function tryNixEval {
+    CODE=$(codeNixEval)
+    echo -e "RUNNING:\n\n$CODE\n\n---\n" >> /dev/stderr
+    echo "$CODE" | nix-shell -p 'haskellPackages.ghcWithPackages (h: [ h.nix-eval ])' --run runhaskell
+}
+
+function codeNixEval {
+  cat <<'EOF'
 import Language.Eval
 
-main = do Just x <- eval (raw "show" $$ raw "True")
+main = do Just x <- eval (raw "show" $$ ((raw "(&&)" $$ raw "True") $$ raw "True"))
           putStrLn x
 EOF
 }
 
-RESULT=$(mkTrue)
+function testNixEval {
+    RESULT=$(tryNixEval)
 
-[[ "x$RESULT" = "xTrue" ]] || fail "Wrong value"
+    [[ "x$RESULT" = "xTrue" ]] || fail "Wrong value"
+
+    echo "testNixEval passed" >> /dev/stderr
+}
+
+function tryMLSpec {
+    CODE=$(codeMLSpec)
+    echo -e "RUNNING:\n\n$CODE\n\n---\n" >> /dev/stderr
+
+    echo "$CODE" | nix-shell -p 'haskellPackages.ghcWithPackages (h: [ h.mlspec h.nix-eval ])' --run runhaskell ||
+        fail "Attempting to evaluate MLSpec-using code aborted"
+}
+
+function codeMLSpec {
+    cat <<'EOF'
+import Language.Eval
+import MLSpec.Theory
+main = do Just x <- runTheory (T [
+            --  E (raw "not",   Ty "Bool -> Bool",         A 1)
+            --, E (raw "True",  Ty "Bool",                 A 0)
+            --, E (raw "False", Ty "Bool",                 A 0)
+            --  E (raw "||",    Ty "Bool -> Bool -> Bool", A 2)
+              E (raw "+", Ty "Int -> Int -> Int", A 2)
+            , E (raw "*", Ty "Int -> Int -> Int", A 2)
+            --, E (raw "&&",    Ty "Bool -> Bool -> Bool", A 2)
+            ])
+          putStrLn x
+EOF
+}
+
+function testMLSpec {
+    RESULT=$(tryMLSpec)
+    JSON=$(echo "$RESULT" | grep -v "^Depth")
+    ALL_LINES=$(echo "$JSON" | wc -l)
+    JSON_LINES=$(echo "$JSON" | grep "^{" | wc -l)
+    [[ "$ALL_LINES" -eq "$JSON_LINES" ]] || {
+        fail "Only '$JSON_LINES'/'$ALL_LINES' look like JSON:\n$RESULT"
+    }
+    echo "testMLSpec passed" >> /dev/stderr
+}
+
+#testNixEval
+testMLSpec
